spring.application.name=url-shortener
# 1. Database Configuration (In-Memory H2 Vault)
spring.datasource.url=jdbc:h2:mem:urldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=URLBNB
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# 2. Tell Spring to use a simple built-in cache instead of requiring a real Redis server today
spring.cache.type=simple